using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using SiyeFlow.Core.Models;

namespace SiyeFlow.Core.TypeGen
{
    class Program
    {
        static void Main(string[] args)
        {
            var outputPath = args.Length > 0 ? args[0] : "../../siye-flow-designer/src/models/workflow-models.ts";
            
            Console.WriteLine("Generating TypeScript definitions from C# models...");
            
            var sb = new StringBuilder();
            
            // Header
            sb.AppendLine("/**");
            sb.AppendLine(" * Auto-generated TypeScript definitions from C# models");
            sb.AppendLine(" * Source: SiyeFlow.Core.Models");
            sb.AppendLine($" * Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine(" * DO NOT EDIT THIS FILE MANUALLY");
            sb.AppendLine(" */");
            sb.AppendLine();
            
            // Generate BlockType enum
            sb.AppendLine("export enum BlockType {");
            foreach (var value in Enum.GetValues<BlockType>())
            {
                var kebabCase = ToKebabCase(value.ToString());
                sb.AppendLine($"    {value} = '{kebabCase}',");
            }
            sb.AppendLine("}");
            sb.AppendLine();
            
            // Generate interfaces
            GenerateInterface<WorkflowDefinition>(sb);
            GenerateInterface<InputDefinition>(sb);
            GenerateInterface<OutputDefinition>(sb);
            
            // Generate abstract WorkflowBlock
            sb.AppendLine("export abstract class WorkflowBlock {");
            sb.AppendLine("    id: string = '';");
            sb.AppendLine("    abstract type: BlockType;");
            sb.AppendLine("    name: string = '';");
            sb.AppendLine("    description?: string;");
            sb.AppendLine("    inputs?: Record<string, string>;");
            sb.AppendLine("    outputs?: Record<string, string>;");
            sb.AppendLine("    onSuccess?: string;");
            sb.AppendLine("    onFailure?: string;");
            sb.AppendLine("    onComplete?: string;");
            sb.AppendLine("}");
            sb.AppendLine();
            
            // Generate concrete block classes
            GenerateBlockClasses(sb);
            
            // Fix SubWorkflowBlock to use Workflow enum value
            sb.Replace("type = BlockType.SubWorkflow;", "type = BlockType.Workflow;");
            
            // Generate union type
            sb.AppendLine("export type AnyWorkflowBlock = ");
            sb.AppendLine("    | StartBlock");
            sb.AppendLine("    | EndBlock");
            sb.AppendLine("    | HttpRequestBlock");
            sb.AppendLine("    | VariableBlock");
            sb.AppendLine("    | ConditionBlock");
            sb.AppendLine("    | DelayBlock");
            sb.AppendLine("    | LogBlock");
            sb.AppendLine("    | EvaluateBlock");
            sb.AppendLine("    | LoopBlock");
            sb.AppendLine("    | CollectBlock");
            sb.AppendLine("    | TryCatchBlock");
            sb.AppendLine("    | SubWorkflowBlock;");
            sb.AppendLine();
            
            // Ensure output directory exists
            var fullPath = Path.GetFullPath(outputPath);
            var directory = Path.GetDirectoryName(fullPath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory!);
            }
            
            // Write file
            File.WriteAllText(fullPath, sb.ToString());
            Console.WriteLine($"TypeScript definitions generated at: {fullPath}");
        }
        
        static void GenerateInterface<T>(StringBuilder sb)
        {
            var type = typeof(T);
            sb.AppendLine($"export interface {type.Name} {{");
            
            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var tsType = GetTypeScriptType(prop.PropertyType);
                var isOptional = IsNullable(prop.PropertyType) ? "?" : "";
                var jsonProperty = prop.GetCustomAttribute<Newtonsoft.Json.JsonPropertyAttribute>();
                var propName = jsonProperty?.PropertyName ?? ToCamelCase(prop.Name);
                
                sb.AppendLine($"    {propName}{isOptional}: {tsType};");
            }
            
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        static void GenerateBlockClasses(StringBuilder sb)
        {
            var blockTypes = new[]
            {
                ("StartBlock", "StartConfig"),
                ("EndBlock", "EndConfig"),
                ("HttpRequestBlock", "HttpRequestConfig"),
                ("VariableBlock", "VariableConfig"),
                ("ConditionBlock", "ConditionConfig"),
                ("DelayBlock", "DelayConfig"),
                ("LogBlock", "LogConfig"),
                ("EvaluateBlock", "EvaluateConfig"),
                ("LoopBlock", "LoopConfig"),
                ("CollectBlock", "CollectConfig"),
                ("TryCatchBlock", "TryCatchConfig"),
                ("SubWorkflowBlock", "SubWorkflowConfig")
            };
            
            foreach (var (blockClass, configClass) in blockTypes)
            {
                // Generate config interface first
                var configType = Type.GetType($"SiyeFlow.Core.Models.{configClass}, SiyeFlow.Core");
                if (configType != null)
                {
                    GenerateInterface(sb, configType);
                }
                
                // Generate block class
                var blockTypeEnum = blockClass.Replace("Block", "");
                sb.AppendLine($"export class {blockClass} extends WorkflowBlock {{");
                sb.AppendLine($"    type = BlockType.{blockTypeEnum};");
                if (configType != null)
                {
                    sb.AppendLine($"    config: {configClass} = new {configClass}();");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }
        
        static void GenerateInterface(StringBuilder sb, Type type)
        {
            sb.AppendLine($"export class {type.Name} {{");
            
            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var tsType = GetTypeScriptType(prop.PropertyType);
                var jsonProperty = prop.GetCustomAttribute<Newtonsoft.Json.JsonPropertyAttribute>();
                var propName = jsonProperty?.PropertyName ?? ToCamelCase(prop.Name);
                var defaultValue = GetDefaultValue(prop.PropertyType);
                var isNullable = IsNullable(prop.PropertyType);
                
                if (isNullable && prop.PropertyType != typeof(string))
                {
                    sb.AppendLine($"    {propName}?: {tsType};");
                }
                else
                {
                    sb.AppendLine($"    {propName}: {tsType} = {defaultValue};");
                }
            }
            
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        static string GetTypeScriptType(Type type)
        {
            if (IsNullable(type))
            {
                type = Nullable.GetUnderlyingType(type) ?? type;
            }
            
            if (type == typeof(string)) return "string";
            if (type == typeof(int) || type == typeof(long) || type == typeof(double) || type == typeof(float) || type == typeof(decimal)) return "number";
            if (type == typeof(bool)) return "boolean";
            if (type == typeof(object)) return "any";
            if (type.IsEnum) return type.Name;
            
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Dictionary<,>))
            {
                var args = type.GetGenericArguments();
                var keyType = GetTypeScriptType(args[0]);
                var valueType = GetTypeScriptType(args[1]);
                return $"Record<{keyType}, {valueType}>";
            }
            
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
            {
                var elementType = GetTypeScriptType(type.GetGenericArguments()[0]);
                return $"{elementType}[]";
            }
            
            if (type.IsArray)
            {
                var elementType = GetTypeScriptType(type.GetElementType()!);
                return $"{elementType}[]";
            }
            
            return type.Name;
        }
        
        static string GetDefaultValue(Type type)
        {
            if (IsNullable(type)) return "undefined";
            if (type == typeof(string)) return "''";
            if (type == typeof(int) || type == typeof(long) || type == typeof(double) || type == typeof(float) || type == typeof(decimal)) return "0";
            if (type == typeof(bool)) return "false";
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Dictionary<,>)) return "{}";
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>)) return "[]";
            if (type.IsArray) return "[]";
            
            return $"new {type.Name}()";
        }
        
        static bool IsNullable(Type type)
        {
            return Nullable.GetUnderlyingType(type) != null || 
                   (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>)) ||
                   (!type.IsValueType && type != typeof(string));
        }
        
        static string ToCamelCase(string str)
        {
            if (string.IsNullOrEmpty(str)) return str;
            return char.ToLowerInvariant(str[0]) + str.Substring(1);
        }
        
        static string ToKebabCase(string str)
        {
            if (string.IsNullOrEmpty(str)) return str;
            
            var result = new StringBuilder();
            for (int i = 0; i < str.Length; i++)
            {
                if (char.IsUpper(str[i]) && i > 0)
                {
                    result.Append('-');
                }
                result.Append(char.ToLowerInvariant(str[i]));
            }
            return result.ToString();
        }
    }
}
