/**
 * Auto-generated TypeScript definitions from C# models
 * Source: SiyeFlow.Core.Models
 * Generated: 2025-11-06 10.13.30
 * DO NOT EDIT THIS FILE MANUALLY
 */

export enum BlockType {
    Start = 'start',
    End = 'end',
    HttpRequest = 'http-request',
    Evaluate = 'evaluate',
    Condition = 'condition',
    Loop = 'loop',
    Delay = 'delay',
    Variable = 'variable',
    Log = 'log',
    Collect = 'collect',
    TryCatch = 'try-catch',
    Workflow = 'workflow',
}

export interface WorkflowDefinition {
    name: string;
    description: string;
    version: string;
    metadata?: Record<string, any>;
    inputs?: Record<string, InputDefinition>;
    outputs?: Record<string, OutputDefinition>;
    blocks?: WorkflowBlock[];
}

export interface InputDefinition {
    type: string;
    required: boolean;
    description: string;
    default?: any;
    value?: any;
}

export interface OutputDefinition {
    type: string;
    value: string;
    description: string;
}

export interface InputProfile {
    name: string;
    description: string;
    default: boolean;
    inputs?: Record<string, InputDefinition>;
}

export interface PortDefinition {
    name: string;
    type: string;
    description: string;
    required: boolean;
    multiple: boolean;
}

export interface PortConnection {
    fromBlock: string;
    fromPort: string;
    toBlock: string;
    toPort: string;
}

export abstract class WorkflowBlock {
    id: string = '';
    abstract type: BlockType;
    name: string = '';
    description?: string;
    inputs?: Record<string, string>;
    outputs?: Record<string, string>;
    onSuccess?: string;
    onFailure?: string;
    onComplete?: string;
    inputPorts?: PortDefinition[];
    outputPorts?: PortDefinition[];
    connections?: PortConnection[];
}

export class StartConfig {
    inputs?: Record<string, InputDefinition>;
    profiles?: InputProfile[];
    selectedProfile: string = '';
    overrides?: Record<string, any>;
}

export class StartBlock extends WorkflowBlock {
    type = BlockType.Start;
    config: StartConfig = new StartConfig();
}

export class EndConfig {
    outputs?: Record<string, OutputDefinition>;
}

export class EndBlock extends WorkflowBlock {
    type = BlockType.End;
    config: EndConfig = new EndConfig();
}

export class HttpRequestConfig {
    method: string = '';
    url: string = '';
    headers?: Record<string, string>;
    body?: any;
    timeout?: number;
    retries?: number;
    successCodes?: number[];
}

export class HttpRequestBlock extends WorkflowBlock {
    type = BlockType.HttpRequest;
    config: HttpRequestConfig = new HttpRequestConfig();
}

export class VariableConfig {
    operation: string = '';
    variables?: Record<string, any>;
}

export class VariableBlock extends WorkflowBlock {
    type = BlockType.Variable;
    config: VariableConfig = new VariableConfig();
}

export class ConditionConfig {
    expression: string = '';
    onTrue: string = '';
    onFalse: string = '';
}

export class ConditionBlock extends WorkflowBlock {
    type = BlockType.Condition;
    config: ConditionConfig = new ConditionConfig();
}

export class DelayConfig {
    milliseconds: number = 0;
    message: string = '';
}

export class DelayBlock extends WorkflowBlock {
    type = BlockType.Delay;
    config: DelayConfig = new DelayConfig();
}

export class LogConfig {
    message: string = '';
    level: string = '';
}

export class LogBlock extends WorkflowBlock {
    type = BlockType.Log;
    config: LogConfig = new LogConfig();
}

export class EvaluateConfig {
    language: string = '';
    expression: string = '';
    data: string = '';
}

export class EvaluateBlock extends WorkflowBlock {
    type = BlockType.Evaluate;
    config: EvaluateConfig = new EvaluateConfig();
}

export class LoopConfig {
    items: string = '';
    itemVariable: string = '';
    indexVariable: string = '';
    loopBlock: string = '';
    maxIterations?: number;
}

export class LoopBlock extends WorkflowBlock {
    type = BlockType.Loop;
    config: LoopConfig = new LoopConfig();
}

export class CollectConfig {
    fromLoop: string = '';
    collectExpression: string = '';
    outputVariable: string = '';
}

export class CollectBlock extends WorkflowBlock {
    type = BlockType.Collect;
    config: CollectConfig = new CollectConfig();
}

export class TryCatchConfig {
    tryBlock: string = '';
    catchBlock: string = '';
    finallyBlock: string = '';
    retries?: number;
    retryDelay?: number;
}

export class TryCatchBlock extends WorkflowBlock {
    type = BlockType.TryCatch;
    config: TryCatchConfig = new TryCatchConfig();
}

export class SubWorkflowConfig {
    workflowId: string = '';
    inputs?: Record<string, any>;
    outputMapping?: Record<string, string>;
}

export class SubWorkflowBlock extends WorkflowBlock {
    type = BlockType.Workflow;
    config: SubWorkflowConfig = new SubWorkflowConfig();
}

export type AnyWorkflowBlock = 
    | StartBlock
    | EndBlock
    | HttpRequestBlock
    | VariableBlock
    | ConditionBlock
    | DelayBlock
    | LogBlock
    | EvaluateBlock
    | LoopBlock
    | CollectBlock
    | TryCatchBlock
    | SubWorkflowBlock;

